### PR TITLE
fixes #92

### LINKED ISSUE #92: Debug the Lambda function on AWS-SAM-LOCAL in Eclipse
Followed below steps:
1.	In the Eclipse Project Explorer, open HelloWorldHandler.java.
2.	Right-click in your Eclipse code window, choose Debug As, and then choose AWS SAM Local.
3.	For this example, leave the Project and Template as they are.
4.	Choose Lambda Function in the Run as field.
5.	Choose GetHelloWorld in the Function identifier field.
6.	For this example, we will provide an Amazon S3 event. Choose Generate next to the Event input box.
7.	Choose a region that has your Amazon S3 bucket.
8.	Enter a valid Amazon S3 bucket name.
9.	Enter a valid Amazon S3 object key, and then choose OK.
10.	On the Save As page, select the current project and enter a name for the event file. In this example, we used s3-event.json.
11.	Choose OK to save the event file and get back to the main dialog box.
12.	Leave the advanced settings as they are. See Advanced Settings to learn more about those fields.
13.	Choose Apply, and then choose Debug.
14.	Had also created docker connection in Eclipse Docker Explorer, which connects successfully

-----------------------------------------------------------------------------------------------------------

Eclipse lambda project not able to connect to docker image on my windows system
lambci/lambda:java8

Got below error in eclipse:

[AWS Toolkit] Running command: C:\Users\XXXXXXX\AppData\Roaming\npm\sam.exe local invoke ExampleFunction --debug-port 5858 --event D:\Projects\lambda-worker\src\test\resources\s3-event.put.json --profile default --template D:\Projects\lambda-worker.serverless.template
[AWS Toolkit] Waiting for SAM Local to attach the port 5858
2017/12/22 15:35:56 Successfully parsed D:\Projects\lambda-worker.serverless.template
2017/12/22 15:35:56 Running AWS SAM projects locally requires Docker. Have you got it installed?
2017/12/22 15:35:56 error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[AWS Toolkit] SAM Local invocation done.

### PR DESCRIPTION
**Pull request by phijacobs**
*Issue #, if available:*
#92 
*Description of changes:*
This pull request resolves the null pointer exception by getting the console for the samLocalProcess multiple times, if necessary.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by zhangzhx** [comment]
Thanks for the contribution. Can you confirm that this contribution is made under the terms of the Apache 2.0 license?

**Comment by phijacobs** [comment]
> Thanks for the contribution. Can you confirm that this contribution is made under the terms of the Apache 2.0 license?

Yes, this contribution is made under the terms of the Apache 2.0 license.

Thanks

**Comment by phijacobs** [comment]
I believe that issue #139 is a duplicate of this.

**Comment by zhangzhx** [comment]
I have tested locally, and I'm good with it. Thanks for the contribution.

Just for you to know, we are now more focusing on support JetBrains world, and we just launched the [full support for Java sam support](https://plugins.jetbrains.com/plugin/11349-aws-toolkit). Feel free to give it a try. It's using the latest version of SAM and it is more powerful and sophisticated than the implementation of Eclipse.

**Pull request merged**
